name: custom_responsive_button
description: A responsive Flutter button widget that adjusts to screen size.  # Make this more descriptive
version: 0.0.1
homepage: https://github.com/UMESH-042/Flutter-package

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets or fonts yet, remove comments to keep it clean
